### ISSUE TITLE
SSL Verification

### ISSUE THREAD

**Issue by miroswan** [theforeman/foreman_api#30]
Foreman is not expected to have a valid certificate. Consequently, it would be best to be able to disable ssl verification upon instantiation of resource classes. I'm finding that I have to do this hack to get around it:

```
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
```

**Comment by GregSutcliffe** [comment]
Closing, this repo is now archived.
