### ISSUE TITLE
ipam option missing from subnet resource

### ISSUE THREAD

**Issue by miroswan** [theforeman/foreman_api#31]
This should be configureable.

**Comment by domcleal** [comment]
Ditto #32.

**Comment by mmoll** [comment]
@domcleal could we disable issues and PRs for this repo? And maybe even clearer than now state in the README and repo description that foreman_api is deprecated and discourage its use?

**Comment by mmoll** [comment]
closing, as this is not maintained.

**Comment by GregSutcliffe** [comment]
Closing, this repo is now archived.
